import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  concepts: [
    {
      type: 'autogenerated',
      dirName: 'concepts'

    }
  ],

  magics: [
    {
      type: 'doc',
      label: 'What is a Magic Cell',
      id: 'magics/index'
    },
    {
      label: '@MAGIC Platform',
      type: 'category',
      items: [
        {
          type: 'autogenerated',
          dirName: 'magics/platform'
        }
      ]
    },
    {
      label: '@MAGIC Channels',
      type: 'category',
      
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/docusaurus-guides',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },

      items: [
        {
          type: 'autogenerated',
          dirName: 'magics/channels',
        },
      ]
    },


  ],

  labs: [
    {
      type: 'autogenerated',
      dirName: 'labs',
    },
  ]
};

export default sidebars;
